### ISSUE TITLE
Segurança da informação

### ISSUE THREAD

**Issue by lucasleal10** [XSilv/Finn#1]
# Variáveis de ambiente

As linhas **10 a 13** do arquivo _main.py_ contém **informações sensíveis e importantes** visto que esses dados podem ser acessados por outras pessoas mal intencionadas. Sugestão de melhoria é usar o que se chama de **_variáveis de ambiente_** para ocultar esses dados importantes e manter seguros suas informações.

**Comment by XSilv** [comment]
Corrigido. Obrigado!
